[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form processing configuration
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Ensure forms are processed
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 